### ISSUE TITLE
ad failed to load

### ISSUE THREAD

**Issue by borut123** [GuJEMSAdTech/gujemsandroidsdk#11]
I'm always getting the following error when trying to load the ad directly from the layout:
E/GuJEMSAdListener: 26148534 ad failed to load: No valid ad found.

 `<de.guj.ems.mobile.sdk.views.GuJEMSAdView
                android:id="@+id/banner_top"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                ems:ems_adUnit="sdktest,1,no" />
`

I'm using the SDK from the latest 2.1 branch, with gradle support.
any idea what am I missing here?

**Comment by mr8ungle** [comment]
Can you elaborate on which app you are integrating the SDK in? Helps us checking the setup for test ads.

Thank you

**Comment by michaelgohl** [comment]
Hello Borut123,

the message means that our ad server couldn't found an ad for your request. Please use an other position (3 or 10). Does it work for that positions?

Best Regards

Micha

**Comment by borut123** [comment]
yes, it works. thanks
