### ISSUE TITLE
Wrong String comparision

### ISSUE THREAD

**Issue by christophwidulle** [GuJEMSAdTech/gujemsandroidsdk#13]
https://github.com/GuJEMSAdTech/gujemsandroidsdk/blob/d69c7ef28dae2d23993ae5c35ad91ddfd84afa75/GuJeMSSDK/src/main/java/de/guj/ems/mobile/sdk/controllers/adserver/DFPSettingsAdapter.java#L176

Should use .equals()

**Comment by daniel-gerold** [comment]
Fixed in 2.1.6
