### ISSUE TITLE
AndroidManifest Permissions Cleanup

### ISSUE THREAD

**Issue by mdivkovic** [GuJEMSAdTech/gujemsandroidsdk#2]
Hey guys,

I noticed in the migration guide from 1.4.x to 2.0.x you mention that

> All SDK permissions other than location adn networking have been commented out in the manifest. Please check the manifest if you previously had certain permissions set, e.g. for camera access or vibration

Here's what could be improved:
1. The VIBRATE permission is currently not commented out or removed from the manifest, but it should be according to the quote from the migration guide above.
2. You don't need the ACCESS_COARSE_LOCATION permission if you already declare the ACCESS_FINE_LOCATION permission. The second one [implicitly grants the first one as well](http://developer.android.com/guide/topics/location/strategies.html#Permission).
3. You don't need the ACCESS_WIFI_STATE permission. I did a full  text search on the project and it doesn't use the WifiManager anywhere - this is what the permission would be necessary for. I only see that the code in SdkUtil is using the ConnectivityManager, which requires the ACCESS_NETWORK_STATE permission, and is enough even to check whether the device has WiFi connectivity. [It's explained in detail here](http://developer.android.com/training/basics/network-ops/managing.html#check-connection). ACCESS_WIFI_STATE is only necessary if you need to access detailed information about individual WiFi connections - which it seems like you don't.

Cheers!

**Comment by mr8ungle** [comment]
Thanks - we have created a JIRA ticket our of your comments and will cleanup the manifest in a coming commit.

Issue will be kept open until change is commited.

**Comment by mdivkovic** [comment]
Great stuff guys :)

**Comment by mr8ungle** [comment]
In branch 2.0.1 the manifest has been cleaned up

**Comment by mdivkovic** [comment]
Awesome, thanks!
