### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by AndreyBulgakow** [GuJEMSAdTech/gujemsandroidsdk#8]
Hi Guys!

It would be very useful for us to have gradle support, because our whole setup is based on Android Studio + gradle. 

Greetings
Andrei from Chefkoch GmbH

**Comment by mr8ungle** [comment]
Hi Andrei - mit dem nächsten Update stellen wir einen Gradle Build zu Verfügung.

Wir melden uns nächste Woche bei euch.

**Comment by giniedp** [comment]
Gradle Build wär schon super. Aktuell mach ich das noch über ein Submodule

im AndroidStudio Projektverzeichnis
`git submodule add git@github.com:GuJEMSAdTech/gujemsandroidsdk.git gujemssdk\source`

dann eine gradle datei erstellen unter `gujemssdk\build.gradle`

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 12
        versionName "2.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    sourceSets {
        main {
            manifest.srcFile 'source/AndroidManifest.xml'
            java.srcDirs = ['source/src']
            res.srcDirs = ['source/res']
        }
    }
}

repositories {
    mavenCentral()
    flatDir{ dirs 'source/libs' }
}

dependencies {
    compile fileTree(dir: 'source/libs', include: ['*.jar'])
    compile 'com.google.android.gms:play-services-ads:8.3.0'
}
```

**Comment by daniel-gerold** [comment]
@AndreyBulgakow @giniedp Mit dem nächsten Commit werden wir einen Grade Build zur Verfügung stellen!
